/* The `OpenAISuggestions` class is a JavaScript class that uses the OpenAI API to generate suggestions
based on a system task and a user task. */
const OpenAI = require('openai');

class OpenAISuggestions {
    constructor(apiKey, gptModel = 'gpt-3.5-turbo-0613') {
        this.openai = new OpenAI({
            apiKey: apiKey
        });

        this.gptModel = gptModel;
    }

    /**
     * The function "suggest" uses OpenAI's chat completions API to generate a response based on a
     * system task and a user task.
     * @param systemTask - The `systemTask` parameter is a string that represents the task or
     * instruction given to the AI model as a system message. It provides context or guidance to the
     * model for generating a response.
     * @param userTask - The `userTask` parameter represents the task or prompt given by the user. It
     * is the content of the message from the user role in the conversation.
     * @returns The content of the message generated by the AI model is being returned.
     */
    async suggest (systemTask, userTask) {
        const aiResponse = await this.openai.chat.completions.create({
            messages: [
                {
                    role: 'system',
                    content: systemTask
                },
                {
                    role: 'user',
                    content: userTask
                }
            ],
            model: this.gptModel || DEFAULT_GPT_MODEL
        });
    
        return aiResponse.choices[0].message.content;
    }
}

module.exports = {
    OpenAISuggestions: OpenAISuggestions
}
